meta_product_name: "My List"
meta_title: "My List - Manage Your Groceries"
meta_description: "MyList is the best application to manage your grocery shopping. Choose recipes and easily know what you need to buy for it."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@LeWagonLondon"   # required for Twitter Cards